### ISSUE TITLE
OSX gitlost not working

### ISSUE THREAD

**Issue by spboyer** [McLeopold/gitlost#2]
```
$ npm install -g gitlost

$ gitlost

** output **
/bin/gitlost: line 1: syntax error near unexpected token `('
/bin/gitlost: line 1: `var opn = require('opn');'
```

**Comment by SaintGimp** [comment]
To solve that immediate problem, the gitlost file needs to have this line added at the top:
`#!/usr/bin/env node`

When I add that line, node is correctly invoked, but then I get another error:
```
(node:54348) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 1
(node:54348) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Scandalon** [comment]
What versions of OS and things? For me on 10.12.5, most things installed via macbrew:

$ which node
/usr/local/bin/node
$ which npm
/usr/local/bin/npm
$ node --version
v8.1.0
$ npm --version
5.0.3

$ npm install -g gitlost
/usr/local/bin/gitlost -> /usr/local/lib/node_modules/gitlost/bin/gitlost.js
+ gitlost@1.0.3
added 12 packages in 1.072s

**Comment by SaintGimp** [comment]
@Scandalon Sure, it installs fine on OSX, but when you run `gitlost` in a terminal window it tries to execute the script as a Bash script, not Javascript.

**Comment by Scandalon** [comment]
Whoops, stupid/obvious mistake. We should delete both these comments.

**Comment by Scandalon** [comment]
![image](https://user-images.githubusercontent.com/1691149/26989315-6cd979c6-4d07-11e7-9eb9-90abfc6631a8.png)

**Comment by OranguTech** [comment]
See PR https://github.com/McLeopold/gitlost/pull/38 - I think I got it solved.
