### ISSUE TITLE
Implement a "zoom to branch" feature

### ISSUE THREAD

**Issue by XeroOne** [McLeopold/gitlost#35]
When I've got dozens of branches in scope and I want to find a specific branch (typically by the user story ID contained in the branch name) I use the browser's find in page feature (ctrl-F).  This used to scroll the branch into view before the D3 pane was implemented.

Can we have a "Search by branch name" feature to scroll the branch into view via the D3 pane?  

If there was an easy click a branch name to zoom to, that would be useful, otherwise I'd search by part of the branch name; which may match multiple branches.  If the latter, I'd need to be able to click next to see the next match. 

Thanks.

**Comment by XeroOne** [comment]
Thank you.  The new version does this quite nicely!

**Comment by McLeopold** [comment]
Added with Vue interface.
